#Работаем с Ubuntu 20.04
---
- name: Setup php-backend

  hosts: 10.128.0.11
  
  become: yes

  tasks:

  - name: add user
    include_role:
      name: users

  - name: install php-fpm
    include_role:
      name: php


- name: Setup www-frontend

  hosts: 10.128.0.11

  become: yes

  tasks:

  - name: add user
    include_role:
      name: users

  - name: install nginx
    include_role:
      name: http
    vars:
      php_host: '{{hostvars[php.example.com][ansible_default_ipv4][address]}}'

